#!/bin/sh

LIBS="\
  jquery/3.2.1/jquery.js \
  knockout/3.4.1/knockout-min.js \
  rateYo/2.2.0/jquery.rateyo.min.css \
  rateYo/2.2.0/jquery.rateyo.min.js \
  "

DIR=src/main/resources/public/cdn-libs

for LIB in $LIBS; do
  mkdir -p "$DIR/`dirname $LIB`"
  curl -s -S -o "$DIR/$LIB" "cdnjs.cloudflare.com/ajax/libs/$LIB"
done
