<header class="main-page-head aqua-body" id="main-page-head">
<#if model.appInHeader!false>
  <div id="root">
    <span id="root-marker"></span>
  </div>
</#if>
  <div class="main-page-logo">
    <a href="/"><img src="/aqua-thumbsup.jpg"></a>
    <div class="start-page-head-text">
      <div class="first-head">Aqua</div>
      <div class="second-head">anime recommendations</div>
    </div>
  </div>
</header>